/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ApiResponseMetadata } from './ApiResponseMetadata';
import {
    ApiResponseMetadataFromJSON,
    ApiResponseMetadataFromJSONTyped,
    ApiResponseMetadataToJSON,
    ApiResponseMetadataToJSONTyped,
} from './ApiResponseMetadata';
import type { ApiLinks } from './ApiLinks';
import {
    ApiLinksFromJSON,
    ApiLinksFromJSONTyped,
    ApiLinksToJSON,
    ApiLinksToJSONTyped,
} from './ApiLinks';
import type { ApiRepositoryUrlResponse } from './ApiRepositoryUrlResponse';
import {
    ApiRepositoryUrlResponseFromJSON,
    ApiRepositoryUrlResponseFromJSONTyped,
    ApiRepositoryUrlResponseToJSON,
    ApiRepositoryUrlResponseToJSONTyped,
} from './ApiRepositoryUrlResponse';

/**
 * 
 * @export
 * @interface ApiRepositoryCollectionUrlResponse
 */
export interface ApiRepositoryCollectionUrlResponse {
    /**
     * Requested Data
     * @type {Array<ApiRepositoryUrlResponse>}
     * @memberof ApiRepositoryCollectionUrlResponse
     */
    data?: Array<ApiRepositoryUrlResponse>;
    /**
     * 
     * @type {ApiLinks}
     * @memberof ApiRepositoryCollectionUrlResponse
     */
    links?: ApiLinks;
    /**
     * 
     * @type {ApiResponseMetadata}
     * @memberof ApiRepositoryCollectionUrlResponse
     */
    meta?: ApiResponseMetadata;
}

/**
 * Check if a given object implements the ApiRepositoryCollectionUrlResponse interface.
 */
export function instanceOfApiRepositoryCollectionUrlResponse(value: object): value is ApiRepositoryCollectionUrlResponse {
    return true;
}

export function ApiRepositoryCollectionUrlResponseFromJSON(json: any): ApiRepositoryCollectionUrlResponse {
    return ApiRepositoryCollectionUrlResponseFromJSONTyped(json, false);
}

export function ApiRepositoryCollectionUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRepositoryCollectionUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(ApiRepositoryUrlResponseFromJSON)),
        'links': json['links'] == null ? undefined : ApiLinksFromJSON(json['links']),
        'meta': json['meta'] == null ? undefined : ApiResponseMetadataFromJSON(json['meta']),
    };
}

export function ApiRepositoryCollectionUrlResponseToJSON(json: any): ApiRepositoryCollectionUrlResponse {
    return ApiRepositoryCollectionUrlResponseToJSONTyped(json, false);
}

export function ApiRepositoryCollectionUrlResponseToJSONTyped(value?: ApiRepositoryCollectionUrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(ApiRepositoryUrlResponseToJSON)),
        'links': ApiLinksToJSON(value['links']),
        'meta': ApiResponseMetadataToJSON(value['meta']),
    };
}

