/* tslint:disable */
/* eslint-disable */
/**
 * ContentSourcesBackend
 * The API for the repositories of the content sources that you can use to create and manage repositories between third-party applications and the [Red Hat Hybrid Cloud Console](https://console.redhat.com). With these repositories, you can build and deploy images using Image Builder for Cloud, on-Premise, and Edge. You can handle tasks, search for required RPMs, fetch a GPGKey from the URL, and list the features within applications. 
 *
 * The version of the OpenAPI document: v1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiRepositoryUrlResponse
 */
export interface ApiRepositoryUrlResponse {
    /**
     * The URL of the repository
     * @type {string}
     * @memberof ApiRepositoryUrlResponse
     */
    url?: string;
}

/**
 * Check if a given object implements the ApiRepositoryUrlResponse interface.
 */
export function instanceOfApiRepositoryUrlResponse(value: object): value is ApiRepositoryUrlResponse {
    return true;
}

export function ApiRepositoryUrlResponseFromJSON(json: any): ApiRepositoryUrlResponse {
    return ApiRepositoryUrlResponseFromJSONTyped(json, false);
}

export function ApiRepositoryUrlResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiRepositoryUrlResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'url': json['url'] == null ? undefined : json['url'],
    };
}

export function ApiRepositoryUrlResponseToJSON(json: any): ApiRepositoryUrlResponse {
    return ApiRepositoryUrlResponseToJSONTyped(json, false);
}

export function ApiRepositoryUrlResponseToJSONTyped(value?: ApiRepositoryUrlResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'url': value['url'],
    };
}

